### ISSUE TITLE
Inconsistent Parameter Order for Agents

### ISSUE THREAD

**Issue by benvoe** [MushroomRL/mushroom-rl#10]
**Describe the bug**
The order of constructor parameters in the agents is not consistant. 

Examples:
Agent(self, policy, mdp_info, features=None)
DeepAC(self, policy, mdp_info, actor_optimizer, parameters)
A2C(self, mdp_info, policy, critic_params, **alg_params)
BlackBoxOptimization(self, distribution, policy, mdp_info, features=None)

**Expected behavior**
I would expect parameters to have the same order and positioning like in its superclass, where ever possible.

Examples:
Agent(self, policy, mdp_info, features=None)
DeepAC(self, policy, mdp_info, actor_optimizer, parameters)
A2C(self, policy, mdp_info, critic_params, **alg_params)
BlackBoxOptimization(self, policy, mdp_info, distribution, features=None)

**System information (please complete the following information):**
- Mushroom version 1.2.0

**Comment by carloderamo** [comment]
Fixed in dev branch.
