### ISSUE TITLE
TypeError while running the file minigrid_dqn.py

### ISSUE THREAD

**Issue by shreyassr123** [MushroomRL/mushroom-rl#148]
I am getting the following TypeError:

 File ~/Desktop/mushroom-rl-master/examples/minigrid_dqn.py:274 in experiment
    mdp = MiniGrid(args.name, history_length=args.history_length)

TypeError: 'NoneType' object is not callable

**Comment by Harry-maximum** [comment]
I think you passed some of the wrong names inside of the args, so I think you need to check your args names carefully?

**Comment by boris-il-forte** [comment]
Sorry for the very late response. I think the issue is simply that you don't have minigrid installed, therefore the class name is not instantiated (it is set to None)
