### ISSUE TITLE
Discretization of the state space

### ISSUE THREAD

**Issue by kishanpb** [MushroomRL/mushroom-rl#23]
Is there an option to discretize the state space of an environment included in this repo?

**Comment by davide-tateo90** [comment]
Not yet, unfortunately. We are thinking of introducing these features in the future releases of mushroom_rl, however, we are quite busy at the moment with the current release, so it might take a while. We might accept a pull request in dev, if you provide clean and well-documented code.

In the meantime, you can implement the discretization by yourself:
1) Create a class that extends the Environment interface
2) Take as input any environment in the constructor
3) create a single set of tiles in the constructor:
```
self.tiles = Tiles.generate(n_tilings=1,
                            n_tiles=n_tiles,
                            low=mdp.info.observation_space.low, 
                            high=mdp.info.observation_space.high)[0]
```
nb: `n_tiles` can be also a vector to have different discretization for every element
in reset and step, call first the original environment method to get the state, and then compute the discretized state by calling the tiles `discrete_state = self.tiles(state)`
This is the easiest and cleanest way to implement environment discretization.
