### ISSUE TITLE
Trying to solve the simple chain environment using LSPI

### ISSUE THREAD

**Issue by kishanpb** [MushroomRL/mushroom-rl#24]
**Describe the bug** A clear and concise description of what the bug is.

In hope of getting features {I(a=L),I(a=L)s,I(a=L)s^2,I(a=R),I(a=R)s,I(a=R)s^2}, I used: 
```
basis = PolynomialBasis.generate(max_degree=2, input_size=2)
features = Features(basis_list=basis)
```

Although, I got an error such as:

>   File "examples/simplechain_lspi.py", line 77, in <module>
>     steps = experiment()
>   File "examples/simplechain_lspi.py", line 57, in experiment
>     core.evaluate(n_episodes=2, render=True)
>   File "/Users/kishanpb/Documents/Github/mushroom-rl/mushroom_rl/core/core.py", line 94, in evaluate
>     initial_states)
>   File "/Users/kishanpb/Documents/Github/mushroom-rl/mushroom_rl/core/core.py", line 123, in _run
>     episodes_progress_bar, render, initial_states)
>   File "/Users/kishanpb/Documents/Github/mushroom-rl/mushroom_rl/core/core.py", line 139, in _run_impl
>     sample = self._step(render)
>   File "/Users/kishanpb/Documents/Github/mushroom-rl/mushroom_rl/core/core.py", line 185, in _step
>     action = self.agent.draw_action(self._state)
>   File "/Users/kishanpb/Documents/Github/mushroom-rl/mushroom_rl/algorithms/agent.py", line 48, in draw_action
>     state = self.phi(state)
>   File "/Users/kishanpb/Documents/Github/mushroom-rl/mushroom_rl/features/_implementations/basis_features.py", line 21, in __call__
>     out[i] = bf(s)
>   File "/Users/kishanpb/Documents/Github/mushroom-rl/mushroom_rl/features/basis/polynomial.py", line 41, in __call__
>     out *= x[i]**d
> IndexError: index 1 is out of bounds for axis 0 with size 1

**To Reproduce** Provide a snippet of code or a Python file. I used cartpole_lspi.py code but with the environment: ```
mdp = generate_simple_chain(state_n=5, goal_states=[2], prob=.8, rew=1,
                                gamma=.9)
``` and the basis features as written before. Code is attached here
[simplechain_lspi.py.zip](https://github.com/MushroomRL/mushroom-rl/files/4340862/simplechain_lspi.py.zip)

**System information (please complete the following information):**
- OS: Mac 10.13.6
- Python version: Python3.7
- Torch version: Pytorch 1.3
- Mushroom version: master

**Comment by davide-tateo90** [comment]
This is not a bug, the behavior is expected. LSPI automatically computes the action features from the state features.  You just need to set use input_size=1, as the state vector has only one component.

Remember also that for the simple chain there is no visualization, so you have to turn off the rendering.

However, you are not supposed to use the polynomial features for finite states, as they are specifically designed for vectors of continuous state-actions.
In our framework the index of the discrete state is not meant to have a meaning, it is just a label for the state. Of course, in a chain, this label is meaningful as it represents the order in the chain.
In general, if you really want to create features for finite-state MDPs, you can just create your own class, implementing the `FeaturesImplementation` (in features._implementations) interface. This will let you choose a reasonable set of features to the MDP, if you have previous information about the state distribution.

I hope this solves your issue.
