### ISSUE TITLE
Question about the RBFs

### ISSUE THREAD

**Issue by kishanpb** [MushroomRL/mushroom-rl#30]
The comments in gaussian_rbf.py say
```
Factory method to build uniformly spaced Gaussian radial basis functions
        with a 25\% overlap.
```
What is meant by the "25% overlap" here? For example, 
![image](https://user-images.githubusercontent.com/9605238/83585543-b8199c00-a50f-11ea-94a5-a2790c9b564e.png) what percentage would these 2 Gaussians overlap with?

A 100% overlap can be thought of as 2 Gaussians of the same parameters. So, an overlap percentage is 100 times the ratio of the common area of 2 Gaussians to the area of one of the Gaussians (since the width parameter is the same across these 2 Gaussians)? If this isn't true, then please let me know what is the formal definition of the "overlap".

**Comment by davide-tateo90** [comment]
yes, the overlap should be the percentage of the area between the two gaussians.

You can find how the computation is done in https://github.com/MushroomRL/mushroom-rl/blob/master/mushroom_rl/utils/features.py
remember that rbf are not gaussians, as they don't have the normalizing factor:

np.exp(-np.sum((x - self._mean)**2 / self._scale))
