### ISSUE TITLE
Segway environment not loaded in init

### ISSUE THREAD

**Issue by rpinsler** [MushroomRL/mushroom-rl#46]
Hi,

The Segway environment is not loaded in `mushroom_rl/environments/__init__.py`, which is confusing when you try to import it. Since it is the only one missing I assume you simply forgot to put it there?

Best,
Robert

**Comment by carloderamo** [comment]
Hi Robert,
thanks for using MushroomRL and reporting this bug. We’ll fix it asap on the dev branch of the library. We are planning to do a new release of the library in few weeks, which will contain this fix among other improvements.
Best wishes,

Carlo D’Eramo

**Comment by rpinsler** [comment]
Fixed in https://github.com/MushroomRL/mushroom-rl/commit/3cd11dfade6d92e99e1092478ce514b44a30707b, thanks!

**Comment by davide-tateo90** [comment]
Thanks for reporting and closing this bug issue.
Due to corona and travel, we are not so fast in the issue response, but we will improve ;)
