### ISSUE TITLE
Could someone show me an example of DQN but using an RNN?

### ISSUE THREAD

**Issue by lionely** [MushroomRL/mushroom-rl#57]
I'm working on a problem with small time-series data. I wrote an environment myself in mushroom.

I wanted to see if DQN where the Q-network is a GRU would help. But I keep running into problems, mainly this:

`RuntimeError: Expected object of scalar type Double but got scalar type Float for argument #3 'mat2' in call to _th_addmm_out
`
I tried  `agents.approximator.model.network = agents.approximator.model.network.double()` and setting the data I use to double() in every step but still it won't work. I'm wondering if somewhere along the line in mushroom things get casted to floats?

Please let me know if anyone has any insight!
I have also attached my network I know it looks gross but I have been trying to track down the problem.

`class GRUNetwork(nn.Module):
    n_features = 64

    def __init__(self, input_shape, output_shape, **kwargs):
        super().__init__()

        n_input = input_shape[0]
        n_output = output_shape[0]
        
        self._gru = nn.GRU(input_size=n_input,hidden_size=self.n_features,batch_first=True)
        self._h1 = nn.Linear(self.n_features,32)
        self._h2 = nn.Linear(32,16)
        self._h3 = nn.Linear(16, n_output)

        nn.init.xavier_uniform_(self._h1.weight,
                                gain=nn.init.calculate_gain('relu'))
        nn.init.xavier_uniform_(self._h2.weight,
                                gain=nn.init.calculate_gain('relu'))
        nn.init.xavier_uniform_(self._h3.weight,
                                gain=nn.init.calculate_gain('linear'))

    def forward(self, state, action=None):
        state = state.type(torch.DoubleTensor)
        #print( state.dtype, state.shape, state.dim() )
        if state.dim() == 2:
            state = state.unsqueeze(1)
        if state.shape[0]==256:
            print(state[0].dtype)
            print(state[0][0].dtype)
            print(state[0])
        self._gru = self._gru.double()
        h,_ = self._gru(state.type(torch.DoubleTensor))
        h = F.relu(h.double())
        h = F.relu(self._h1(h.double()))
        h = F.relu(self._h2(h.double()))
        q = self._h3(h.double())

        if action is None:
            return q
        else:
            q_acted = torch.squeeze(q.gather(1, action.long()))

            return q_acted`

**Comment by lionely** [comment]
Nevermind I tried harder and figured it out. Sorry for waste of space.

**Comment by davide-tateo90** [comment]
No worries. Keep in mind that, probably, if you are training RNN you should sample sequences from the RNN. This means that you should modify the replay memory accordingly. Right now mushroom doesn't contain any replay memory that is well suited for RNN...
