### ISSUE TITLE
Please add hyper-parameter tuning options?

### ISSUE THREAD

**Issue by lionely** [MushroomRL/mushroom-rl#58]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

[Stable baselines 3](https://github.com/DLR-RM/stable-baselines3) supports hyperparameter tuning with [Optuna](https://github.com/optuna/optuna). It would be really helpful if this is was supported in Mushroom-RL. It's a bit difficult now since all the training logic is hidden in core.learn().

**Comment by carloderamo** [comment]
Optuna can be used easily in MushroomRL without the need of changing the core. Actually it is not clear why you are referring to the core.learn function, and I think what you can simply do is to call Optuna in your experiment script. If you need to call Optuna during learning for some reasons, e.g. after each step/episode, you should consider using the already provided callbacks.

**Comment by lionely** [comment]
Ah yes sorry, I actually misunderstood how Optuna worked. Sorry for the misunderstanding!
