### ISSUE TITLE
Question: Can I create a completely custom environment?

### ISSUE THREAD

**Issue by Jeonous** [MushroomRL/mushroom-rl#64]
Hi.

I want to create totally new vectorized environment that is not presented by any library.
And I tried to create it using the MushroomRL library.

However, though I read and followed the MushrromRL Document, I couldn't generate my custom environment.

URL I referenced:
https://mushroomrl.readthedocs.io/en/latest/source/tutorials/tutorials.5_environments.html#creating-a-new-environment

I thought I could create a custom environment with the MushroomRL library.
Is there anything I'm missing or misunderstood?

**Comment by carloderamo** [comment]
Hi,
MushroomRL does not support vectorized environments at the moment. For regular environments, you are free to create custom environments as described in the doc page you mentioned.

Please, if you need further help, provide more details about the implementation problems you have.

Thanks!

**Comment by Jeonous** [comment]
Thanks for your reply, @carloderamo.

I want to define 10 states and 5 actions.
I also want to create a custom reward function, state transition function, etc. for the states and actions.

But in the document, "Creating a new environment" page, I couldn't find the part, but I could find a 'Circle Environment'.
https://mushroomrl.readthedocs.io/en/latest/source/tutorials/tutorials.5_environments.html#creating-a-new-environment

It seems that if I want to define 'State change according to action' and 'reward', I can use the "step()" method. 
And I can define the custom 5 actions using _Discrete(5)_.
but I couldn't find the part to define custom 10 states.

I thought that the variables _self._size_, _self._goal_, and _self._goal_radius_ seems to be variables for the 'Circle Environment'. 
What method can I use to define custom 10 states?

Thanks!

**Comment by carloderamo** [comment]
Hi,

from what I understand you want to create an environment with 5 discrete actions and 10 discrete states. I suggest taking a look at mushroom/environments/grid_world.py to have an idea of how this should be done.

**Comment by Jeonous** [comment]
@carloderamo  Thank you for the quick reply!

In fact, as I continued reading your code on GitHub, there was something I misunderstood.

I'll also read the .py file you mentioned. Thank you.
