### ISSUE TITLE
Can support multi-agent env and algorithms?

### ISSUE THREAD

**Issue by jluo93** [MushroomRL/mushroom-rl#71]
Can mushroom-rl support multi-agent or will add in the future?

**Comment by davide-tateo90** [comment]
We are thinking about this feature, but we are not sure yet when we will have time or a sufficient workforce to implement this.
This heavily depends if our research will consider multiagent stuff in the future (which is highly plausible).

Actually, we have already a multiagent environment, which is the air hockey environment. You can find it in the dev branch.

However, we neither have any multiagent learning agent, nor direct support for it. If you want to implement a multiagent learning algorithm, what is needed is to wrap every agent in the system in a single MushroomRL agent, which provides a single action vector for every agent. Thus we support only synchronous acting.

In the future, we might consider a multiagent interface for MushroomRL, but the development is still far in the future.
