### ISSUE TITLE
can not import

### ISSUE THREAD

**Issue by potato23333** [MushroomRL/mushroom-rl#72]
Hi, I can not import the package. Error information is as follows:
`  File "mushroom_rl\environments\mujoco_envs\humanoid_gait\_external_simulation\muscle_simulation_stepupdate.pyx", line 1, in init mushroom_rl.environments.mujoco_envs.humanoid_gait._external_simulation.muscle_simulation_stepupdate
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject`

**Comment by davide-tateo90** [comment]
This is a cython + numpy issue. You probably updated numpy to a version that breaks binary compatibility, but you compiled the cython files with the older version. Try to reinstall MushroomRL, this should trigger the compilation again and fix the issue.

**Comment by potato23333** [comment]
Thanks!
