### ISSUE TITLE
Does MushroomRL support environment parallelization.

### ISSUE THREAD

**Issue by ChenDRAG** [MushroomRL/mushroom-rl#83]
I wound like to run Mujoco environments with MushroomRL. However, on my computer, running PPO alogirithm for 1M steps in HalfCheetah would take like more than 1 hour. I think environment parallelization can greatly reduce the required time but haven't figured out the way to use vector environments. Any suggestions?

**Comment by davide-tateo90** [comment]
No, you cannot use environment parallelization in mushroom.
It's also not planned to be implemented in the short term. There are many software reasons that bring us to this decision.
The fact that we don't support parallel execution gives us a very clean and simple framework for every algorithm. As this is a research tool, having good and easy-to-extend implementations is more valuable than speed: indeed in research, you need to run multiple runs with different seeds, so the parallelization is useless.

What you can do, is to implement your own core that does parallel execution of policies. However, we will not merge it in mushroom, at least in the short term, as this brings a lot of software issues and usage issues that we don't want to handle.
